version: '3'
services:
  db:
    image: postgres
    ports:
      - "5433:5432"
    command:
      - "-h"
      - "0.0.0.0"
      - "-c"
      - "log_destination=stderr"
      - "-c"
      - "log_connections=yes"
      - "-c"
      - "log_disconnections=yes"
      - "-c"
      - "log_statement=all"
    volumes:
      - ./local_dev/db_init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: 'assignment'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: '1234'
    restart: 'always'
